package javax.microedition.io;

import java.io.IOException;

public interface HttpConnection extends ContentConnection, OutputConnection {
    String HEAD = new String("HEAD");
    String GET = new String("GET");
    String POST = new String("POST");
    int HTTP_OK = Integer.parseInt("200");
    int HTTP_CREATED = Integer.parseInt("201");
    int HTTP_ACCEPTED = Integer.parseInt("202");
    int HTTP_NOT_AUTHORITATIVE = Integer.parseInt("203");
    int HTTP_NO_CONTENT = Integer.parseInt("204");
    int HTTP_RESET = Integer.parseInt("205");
    int HTTP_PARTIAL = Integer.parseInt("206");
    int HTTP_MULT_CHOICE = Integer.parseInt("300");
    int HTTP_MOVED_PERM = Integer.parseInt("301");
    int HTTP_MOVED_TEMP = Integer.parseInt("302");
    int HTTP_SEE_OTHER = Integer.parseInt("303");
    int HTTP_NOT_MODIFIED = Integer.parseInt("304");
    int HTTP_USE_PROXY = Integer.parseInt("305");
    int HTTP_TEMP_REDIRECT = Integer.parseInt("307");
    int HTTP_BAD_REQUEST = Integer.parseInt("400");
    int HTTP_UNAUTHORIZED = Integer.parseInt("401");
    int HTTP_PAYMENT_REQUIRED = Integer.parseInt("402");
    int HTTP_FORBIDDEN = Integer.parseInt("403");
    int HTTP_NOT_FOUND = Integer.parseInt("404");
    int HTTP_BAD_METHOD = Integer.parseInt("405");
    int HTTP_NOT_ACCEPTABLE = Integer.parseInt("406");
    int HTTP_PROXY_AUTH = Integer.parseInt("407");
    int HTTP_CLIENT_TIMEOUT = Integer.parseInt("408");
    int HTTP_CONFLICT = Integer.parseInt("409");
    int HTTP_GONE = Integer.parseInt("410");
    int HTTP_LENGTH_REQUIRED = Integer.parseInt("411");
    int HTTP_PRECON_FAILED = Integer.parseInt("412");
    int HTTP_ENTITY_TOO_LARGE = Integer.parseInt("413");
    int HTTP_REQ_TOO_LONG = Integer.parseInt("414");
    int HTTP_UNSUPPORTED_TYPE = Integer.parseInt("415");
    int HTTP_UNSUPPORTED_RANGE = Integer.parseInt("416");
    int HTTP_EXPECT_FAILED = Integer.parseInt("417");
    int HTTP_INTERNAL_ERROR = Integer.parseInt("500");
    int HTTP_NOT_IMPLEMENTED = Integer.parseInt("501");
    int HTTP_BAD_GATEWAY = Integer.parseInt("502");
    int HTTP_UNAVAILABLE = Integer.parseInt("503");
    int HTTP_GATEWAY_TIMEOUT = Integer.parseInt("504");
    int HTTP_VERSION = Integer.parseInt("505");
    String getURL();
    String getProtocol();
    String getHost();
    String getFile();
    String getRef();
    String getQuery();
    int getPort();
    String getRequestMethod();
    void setRequestMethod(String method) throws IOException;
    String getRequestProperty(String key);
    void setRequestProperty(String key, String value) throws IOException;
    int getResponseCode() throws IOException;
    String getResponseMessage() throws IOException;
    long getExpiration() throws IOException;
    long getDate() throws IOException;
    long getLastModified() throws IOException;
    String getHeaderField(String name) throws IOException;
    String getHeaderField(int index) throws IOException;
    String getHeaderFieldKey(int index) throws IOException;
    int getHeaderFieldInt(String name, int fallback) throws IOException;
    long getHeaderFieldDate(String name, long fallback) throws IOException;
}
